### ISSUE TITLE
Remove duplicative tests

### ISSUE THREAD

**Issue by mraineri** [DMTF/Redfish-Service-Conformance-Check#177]
There are many tests in the tool that validate things performed by other validators (specifically payload conformance). These tests should be removed, and the tool should focus on the protocol aspects of testing (HTTP headers, response codes, client payload handling, security, etc).

**Comment by billdodd** [comment]
I've started looking through the assertions to identify ones that are duplicative or otherwise out-of-scope for this tool. I will keep notes here with that analysis.

- **TEST_datamodel_schema.py**: The tests in this module validate the DMTF schemas or validate that service resource payloads adhere to the schemas. **All** the assertions in this model are (or should be) covered by the Redfish-Service-Validator (RSV), tools in  https://github.com/DMTF/Redfish-Tools, or Travis CI tests in https://github.com/DMTF/Redfish. So this module can be eliminated entirely.
