### ISSUE TITLE
What is the test doing in 6.5.6.6?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#89]
Seems to be trying to generate a 301 error return.
But I am not able to comprehend the logic.
Can this be explained?

**Comment by billdodd** [comment]
It's trying to trigger a redirect (301) by changing a uri like `/redfish/v1/bar/` to `/redfish/v1/bar` (by stripping off the last character) and doing a GET on that new uri. That is the type of situation that will often trigger a redirect. But there a couple of problems with the current code:
- If the uri is something like `/redfish/v1/bar`, stripping off the last character results in `/redfish/v1/ba`, which will almost certainly not get the expected behavior.
- There is no requirement in the Redfish spec or http specs that the example given (`/redfish/v1/bar/` to `/redfish/v1/bar`) will result in a redirect.

I think the code should be updated to do the following:
- If the uri ends in '/', remove it.
- If the uri does not end in '/', append one.
- Do not fail if the request returns a status other than 301.
- Continue to confirm a Location header is returned IF a 301 status is returned (and fail if the Location header is absent)
